module.exports = [
    {
        title: 'Limagrain',
        subtitle: 'Field Seeds',
        url: 'project/limagrain',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/limagrain/1.png',
        images: ['/works/limagrain/1.png','/works/limagrain/2.png','/works/limagrain/3.png'],
        clientIndustry: 'Seeds',
        contentLink: 'https://lgseeds.com.tr',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'MikroX',
        subtitle: 'Accounting',
        url: 'project/mikrox',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/mikrox/1.png',
        images: ['/works/mikrox/1.png','/works/mikrox/2.png','/works/mikrox/3.png'],
        clientIndustry: 'Accounting & Software',
        contentLink: 'http://mikrox.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Kaleidon',
        subtitle: 'Supplement Products',
        url: 'project/kaleidon',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/kaleidon/1.png',
        images: ['/works/kaleidon/1.png','/works/kaleidon/2.png','/works/kaleidon/3.png','/works/kaleidon/4.png'],
        clientIndustry: 'Supplement',
        contentLink: 'http://kaleidon.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Kırayteks',
        subtitle: 'Textile',
        url: 'project/kirayteks',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/kirayteks/1.png',
        images: ['/works/kirayteks/1.png','/works/kirayteks/2.png','/works/kirayteks/3.png'],
        clientIndustry: 'Textile',
        contentLink: 'http://kirayteks.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },

    {
        title: 'Orhan Education Foundation',
        subtitle: 'Foundation',
        url: 'project/orhan',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/orhanegitim/1.png',
        images: ['/works/orhanegitim/1.png','/works/orhanegitim/2.png'],
        clientIndustry: 'Foundation',
        contentLink: 'https://oekv.org.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Emek Oil',
        subtitle: 'Food',
        url: 'project/emek',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/emekyag/1.png',
        images: ['/works/emekyag/1.png','/works/emekyag/2.png','/works/emekyag/3.png'],
        clientIndustry: 'Oil Products',
        contentLink: 'http://emekyag.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Grup Medika',
        subtitle: 'Medical Center',
        url: 'project/grupmedika',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/grupmedika/1.png',
        images: ['/works/grupmedika/1.png','/works/grupmedika/2.png','/works/grupmedika/3.png','/works/grupmedika/4.png'],
        clientIndustry: 'Medical Center',
        contentLink: 'http://grupmedika.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Brev Yapı',
        subtitle: 'Construction',
        url: 'project/brev',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/brev/1.png',
        images: ['/works/brev/1.png','/works/brev/2.png','/works/brev/3.png','/works/brev/4.png'],
        clientIndustry: 'Building & Construction',
        contentLink: 'http://brevyapi.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'GRL',
        subtitle: 'Vehicle Seats',
        url: 'project/grl',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/grl/1.png',
        images: ['/works/grl/1.png','/works/grl/2.png'],
        clientIndustry: 'Seat',
        contentLink: 'http://grl.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Buket Efendioğlu',
        subtitle: 'Architecture',
        url: 'project/buket',
        type: 'Portfolio',
        image: 'https://novembros.co/berkay/works/buketefendioglu/1.png',
        images: ['/works/buketefendioglu/1.png','/works/buketefendioglu/2.png','/works/buketefendioglu/3.png'],
        clientIndustry: 'Architecture & Design',
        contentLink: 'http://buketefendioglu.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Alper Aytaç',
        subtitle: 'Product Designer',
        url: 'project/alperaytac',
        type: 'Portfolio',
        image: 'https://novembros.co/berkay/works/alperaytac/2.png',
        images: ['/works/alperaytac/2.png','/works/alperaytac/1.png'],
        clientIndustry: 'Design',
        contentLink: 'https://alperaytac.co.uk/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'BeyKem Law',
        subtitle: 'Law Firm',
        url: 'project/beykem',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/beykem/1.png',
        images: ['/works/beykem/1.png','/works/beykem/2.png'],
        clientIndustry: 'Law',
        contentLink: 'http://beykemhukuk.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'BreadHouse',
        subtitle: 'Bakery',
        url: 'project/breadhouse',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/breadhouse/1.png',
        images: ['/works/breadhouse/1.png','/works/breadhouse/2.png'],
        clientIndustry: 'Bakery Products',
        contentLink: 'http://breadhouse.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Capella&Co',
        subtitle: 'Architecture',
        url: 'project/capella',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/capella/1.png',
        images: ['/works/capella/1.png','/works/capella/2.png'],
        clientIndustry: 'Architecture & Design',
        contentLink: 'http://capellaandco.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Cemka',
        subtitle: 'Fabric',
        url: 'project/cemka',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/cemka/1.png',
        images: ['/works/cemka/1.png','/works/cemka/2.png'],
        clientIndustry: 'Polyurethane & Fabric',
        contentLink: 'http://cemka.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Çiftyıldız',
        subtitle: 'Marble',
        url: 'project/ciftyildiz',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ciftyildiz/1.png',
        images: ['/works/ciftyildiz/1.png','/works/ciftyildiz/2.png','/works/ciftyildiz/3.png','/works/ciftyildiz/4.png'],
        clientIndustry: 'Marble',
        contentLink: 'http://ciftyildiz.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Cüneyt Ş.',
        subtitle: 'Portfolio',
        url: 'project/cuneyt',
        type: 'Portfolio',
        image: 'https://novembros.co/berkay/works/cuneytsenyavas/1.png',
        images: ['/works/cuneytsenyavas/1.png'],
        clientIndustry: 'Art & Design',
        contentLink: 'http://cuneytsenyavas.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Dentaplan',
        subtitle: 'Dental Clinic',
        url: 'project/dentaplan',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/dentaplan/1.png',
        images: ['/works/dentaplan/1.png','/works/dentaplan/2.png'],
        clientIndustry: 'Dent',
        contentLink: 'http://dentaplan.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Dorrek',
        subtitle: 'Advertising',
        url: 'project/dorrek',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/dorrek/1.png',
        images: ['/works/dorrek/1.png','/works/dorrek/2.png'],
        clientIndustry: 'Advertising',
        contentLink: 'http://dorrek.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },

    {
        title: 'EKM Engineering',
        subtitle: 'Custom Projects',
        url: 'project/ekm',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ekmmuhendis/1.png',
        images: ['/works/ekmmuhendis/1.png','/works/ekmmuhendis/2.png'],
        clientIndustry: 'Engineering',
        contentLink: 'http://ekmmuhendislikmimarlik.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Elvan Kanat',
        subtitle: 'Healthy Life Center',
        url: 'project/elvan',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/elvan/1.png',
        images: ['/works/elvan/1.png','/works/elvan/2.png'],
        clientIndustry: 'Healthy Life Center',
        contentLink: 'http://elvankanatsaglikliyasammerkezi.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },

    {
        title: 'Ergül Candies',
        subtitle: 'Food',
        url: 'project/ergul',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ergul/1.png',
        images: ['/works/ergul/1.png','/works/ergul/2.png'],
        clientIndustry: 'Food',
        contentLink: 'http://ergulsekerleme.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    // {
    //     title: 'Eyedius',
    //     subtitle: 'Smart Security',
    //     url: 'project/eyedius',
    //     type: 'Corporate',
    //     image: 'https://novembros.co/berkay/works/eyedius/1.png',
    //     images: ['/works/eyedius/1.png','/works/eyedius/2.png'],
    //     clientIndustry: 'Security',
    //     contentLink: 'http://eyedius.com/',
    //     contentType: 'WordPress',
    //     contentDescription: 'etc'
    // },
    {
        title: 'Fordent',
        subtitle: 'Medical Products',
        url: 'project/fordent',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/fordent/1.png',
        images: ['/works/fordent/1.png','/works/fordent/2.png'],
        clientIndustry: 'Medical',
        contentLink: 'http://fordentmedikal.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Güneşoğlu',
        subtitle: 'Dairy Products',
        url: 'project/gunesoglu',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/gunesoglu/1.png',
        images: ['/works/gunesoglu/1.png','/works/gunesoglu/2.png'],
        clientIndustry: 'Dairy Products',
        contentLink: 'http://gunesoglu.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Ilesbus',
        subtitle: 'VIP Buses',
        url: 'project/ilesbus',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ilesbus/1.png',
        images: ['/works/ilesbus/1.png','/works/ilesbus/2.png'],
        clientIndustry: 'VIP Buses',
        contentLink: 'http://ilesbus.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    // {
    //     title: 'Iossmed',
    //     subtitle: 'Medical Products',
    //     url: 'project/iossmed',
    //     type: 'Corporate',
    //     image: 'https://novembros.co/berkay/works/iossmed/1.png',
    //     images: ['/works/iossmed/1.png','/works/iossmed/2.png'],
    //     clientIndustry: 'Medical',
    //     contentLink: 'http://iossmed.com/',
    //     contentType: 'WordPress',
    //     contentDescription: 'etc'
    // },

    {
        title: 'Kumartaşlı',
        subtitle: 'Egg',
        url: 'project/kumartasli',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/kumartasli/1.png',
        images: ['/works/kumartasli/1.png','/works/kumartasli/2.png'],
        clientIndustry: 'Egg & Farm',
        contentLink: 'http://kumartasli.com.tr/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },

    {
        title: 'Maristan Dent',
        subtitle: 'Dental Clinic',
        url: 'project/maristandis',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/maristandis/1.png',
        images: ['/works/maristandis/1.png','/works/maristandis/2.png'],
        clientIndustry: 'Dent',
        contentLink: 'http://maristandis.com/',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    // {
    //     title: 'MB Hospitality Furniture',
    //     subtitle: 'Chair & Furniture',
    //     url: 'project/mbhospitality',
    //     type: 'Corporate',
    //     image: 'https://novembros.co/berkay/works/mbhospitality/1.png',
    //     images: ['/works/mbhospitality/1.png','/works/mbhospitality/2.png'],
    //     clientIndustry: 'Chair & Furniture',
    //     contentLink: 'http://maristandis.com/',
    //     contentType: 'WordPress',
    //     contentDescription: 'etc'
    // },

    {
        title: 'Nordic Coffee',
        subtitle: 'Coffee',
        url: 'project/nordic',
        type: 'Online Menu',
        image: 'https://novembros.co/berkay/works/nordic/1.png',
        images: ['/works/nordic/1.png','/works/nordic/2.png'],
        clientIndustry: 'Coffee',
        contentLink: 'http://nordiccoffee.com.tr/menu',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Norsemont Mining',
        subtitle: 'Mining Company',
        url: 'project/norsemont',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/norsemont/1.png',
        images: ['/works/norsemont/1.png','/works/norsemont/2.png'],
        clientIndustry: 'Mining',
        contentLink: 'http://norsemont.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Oliva',
        subtitle: 'Home Care',
        url: 'project/oliva',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/olivaevde/1.png',
        images: ['/works/olivaeevde/1.png','/works/olivaevde/2.png'],
        clientIndustry: 'Home Care & Health',
        contentLink: 'http://olivaevdebakim.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },

    {
        title: 'Pakfiks Textile',
        subtitle: 'Textile',
        url: 'project/pakfiks',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/pakfiks/1.png',
        images: ['/works/pakfiks/1.png','/works/pakfiks/2.png'],
        clientIndustry: 'Textile',
        contentLink: 'http://pakfiks.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'PMS',
        subtitle: 'Aluminum',
        url: 'project/pms',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/pms/1.png',
        images: ['/works/pms/1.png','/works/pms/2.png'],
        clientIndustry: 'Aluminum',
        contentLink: 'http://pmsaluminyum.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Ponimak',
        subtitle: 'Machines',
        url: 'project/ponimak',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ponimak/1.png',
        images: ['/works/ponimak/1.png','/works/ponimak/2.png'],
        clientIndustry: 'Machine',
        contentLink: 'http://ponimak.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Sedat Demir',
        subtitle: 'Doctor',
        url: 'project/sedatdemir',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/profdrsedat/1.png',
        images: ['/works/profdrsedat/1.png','/works/profdrsedat/2.png'],
        clientIndustry: 'Health',
        contentLink: 'http://profdrsedatdemir.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Selenay Medical Center',
        subtitle: 'Medical',
        url: 'project/selenay',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/selenay/1.png',
        images: ['/works/selenay/1.png','/works/selenay/2.png'],
        clientIndustry: 'Medical',
        contentLink: 'http://selenaytipmerkezi.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Selko',
        subtitle: 'Farm Products',
        url: 'project/selko',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/selko/1.png',
        images: ['/works/selko/1.png','/works/selko/2.png'],
        clientIndustry: 'Farm Products',
        contentLink: 'http://selkotarim.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Teknokol',
        subtitle: 'Support Arm Systems',
        url: 'project/teknokol',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/teknokol/1.png',
        images: ['/works/teknokol/1.png','/works/teknokol/2.png'],
        clientIndustry: 'Industry',
        contentLink: 'http://teknokol.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    // {
    //     title: 'Turkish Blueberry',
    //     subtitle: 'Food & Farm',
    //     url: 'project/turkishblueberry',
    //     type: 'Corporate',
    //     image: 'https://novembros.co/berkay/works/turkishblueberry/1.png',
    //     images: ['/works/turkishblueberry/1.png','/works/turkishblueberry/2.png'],
    //     clientIndustry: 'Food',
    //     contentLink: 'http://turkishblueberry.com',
    //     contentType: 'WordPress',
    //     contentDescription: 'etc'
    // },
    {
        title: 'Umay',
        subtitle: 'Museum Design',
        url: 'project/umaymdt',
        type: 'Portfolio',
        image: 'https://novembros.co/berkay/works/umaymuseum/1.png',
        images: ['/works/umaymuseum/1.png','/works/umaymuseum/2.png'],
        clientIndustry: 'Portfolio',
        contentLink: 'http://umaymdt.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    {
        title: 'Ustade',
        subtitle: 'Food',
        url: 'project/ustade',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/ustade/1.png',
        images: ['/works/ustade/1.png','/works/ustade/2.png'],
        clientIndustry: 'Food',
        contentLink: 'http://ustade.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    // {
    //     title: 'Valorem',
    //     subtitle: 'Personal Growth',
    //     url: 'project/valorem',
    //     type: 'Blog',
    //     image: 'https://novembros.co/berkay/works/valorem/1.png',
    //     images: ['/works/valorem/1.png','/works/valorem/2.png'],
    //     clientIndustry: 'Blog',
    //     contentLink: 'http://valoremgrup.com.tr',
    //     contentType: 'WordPress',
    //     contentDescription: 'etc'
    // },
    {
        title: 'VR Kronos',
        subtitle: 'Virtual Reality',
        url: 'project/vrkronos',
        type: 'Corporate',
        image: 'https://novembros.co/berkay/works/vrkronos/1.png',
        images: ['/works/vrkronos/1.png','/works/vrkronos/2.png'],
        clientIndustry: 'VR',
        contentLink: 'http://vrkronos.com',
        contentType: 'WordPress',
        contentDescription: 'etc'
    },
    
    
  ];
  